"""initial schema

Revision ID: 06899c059cb4
Revises: 
Create Date: 2026-07-23 05:26:38.006795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06899c059cb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_alloy',
    sa.Column('alloy_name', sa.String(length=32), nullable=False),
    sa.Column('main_element', sa.String(length=32), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('alloy_name')
    )
    op.create_table('dim_indicator',
    sa.Column('indicator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('std_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('indicator_id')
    )
    op.create_table('dim_price',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('dim_scrap_type',
    sa.Column('scrap_type', sa.String(length=32), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('impurity_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scrap_type')
    )
    op.create_table('dim_steel_grade',
    sa.Column('steel_grade', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('standard', sa.String(length=128), nullable=True),
    sa.Column('spec_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('steel_grade')
    )
    op.create_table('fact_heat',
    sa.Column('heat_no', sa.String(length=32), nullable=False),
    sa.Column('tap_time', sa.DateTime(), nullable=True),
    sa.Column('steel_grade', sa.String(length=64), nullable=True),
    sa.Column('process_route', sa.String(length=16), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('equipment', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('heat_no')
    )
    op.create_table('fact_heat_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heat_no', sa.String(length=32), nullable=False),
    sa.Column('tap_time', sa.DateTime(), nullable=True),
    sa.Column('steel_grade', sa.String(length=64), nullable=True),
    sa.Column('process_route', sa.String(length=16), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('equipment', sa.String(length=8), nullable=True),
    sa.Column('process', sa.String(length=16), nullable=False),
    sa.Column('indicator_name', sa.String(length=64), nullable=False),
    sa.Column('std_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('judge', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heat_no', 'process', 'indicator_name', name='uq_indicator')
    )
    op.create_index(op.f('ix_fact_heat_indicator_heat_no'), 'fact_heat_indicator', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_heat_indicator_indicator_name'), 'fact_heat_indicator', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_fact_heat_indicator_judge'), 'fact_heat_indicator', ['judge'], unique=False)
    op.create_index(op.f('ix_fact_heat_indicator_process'), 'fact_heat_indicator', ['process'], unique=False)
    op.create_index(op.f('ix_fact_heat_indicator_steel_grade'), 'fact_heat_indicator', ['steel_grade'], unique=False)
    op.create_index(op.f('ix_fact_heat_indicator_tap_time'), 'fact_heat_indicator', ['tap_time'], unique=False)
    op.create_table('fact_heat_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heat_no', sa.String(length=32), nullable=False),
    sa.Column('furnace_batch_no', sa.String(length=32), nullable=True),
    sa.Column('sample_lot_no', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_heat_relation_furnace_batch_no'), 'fact_heat_relation', ['furnace_batch_no'], unique=False)
    op.create_index(op.f('ix_fact_heat_relation_heat_no'), 'fact_heat_relation', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_heat_relation_sample_lot_no'), 'fact_heat_relation', ['sample_lot_no'], unique=False)
    op.create_table('fact_heating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('furnace_batch_no', sa.String(length=32), nullable=True),
    sa.Column('material_no', sa.String(length=32), nullable=True),
    sa.Column('roll_plan_no', sa.String(length=32), nullable=True),
    sa.Column('in_out_flag', sa.String(length=8), nullable=True),
    sa.Column('material_len', sa.Float(), nullable=True),
    sa.Column('in_weight', sa.Float(), nullable=True),
    sa.Column('in_actual_temp', sa.Float(), nullable=True),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('out_temp', sa.Float(), nullable=True),
    sa.Column('total_heat_time', sa.Float(), nullable=True),
    sa.Column('preheat_temp', sa.Float(), nullable=True),
    sa.Column('heat_section_temp', sa.Float(), nullable=True),
    sa.Column('soak_temp', sa.Float(), nullable=True),
    sa.Column('smoke_temp', sa.Float(), nullable=True),
    sa.Column('exhaust_temp', sa.Float(), nullable=True),
    sa.Column('furnace_pressure', sa.Float(), nullable=True),
    sa.Column('steam_pressure', sa.Float(), nullable=True),
    sa.Column('hot_air_temp', sa.Float(), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('shift', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_heating_furnace_batch_no'), 'fact_heating', ['furnace_batch_no'], unique=False)
    op.create_index(op.f('ix_fact_heating_heat_no'), 'fact_heating', ['heat_no'], unique=False)
    op.create_table('fact_inspect_chem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_lot_no', sa.String(length=32), nullable=True),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('C', sa.Float(), nullable=True),
    sa.Column('Si', sa.Float(), nullable=True),
    sa.Column('Mn', sa.Float(), nullable=True),
    sa.Column('P', sa.Float(), nullable=True),
    sa.Column('S', sa.Float(), nullable=True),
    sa.Column('Cu', sa.Float(), nullable=True),
    sa.Column('Ni', sa.Float(), nullable=True),
    sa.Column('Cr', sa.Float(), nullable=True),
    sa.Column('Mo', sa.Float(), nullable=True),
    sa.Column('V', sa.Float(), nullable=True),
    sa.Column('Nb', sa.Float(), nullable=True),
    sa.Column('Ti', sa.Float(), nullable=True),
    sa.Column('Al', sa.Float(), nullable=True),
    sa.Column('Als', sa.Float(), nullable=True),
    sa.Column('Alt', sa.Float(), nullable=True),
    sa.Column('Ca', sa.Float(), nullable=True),
    sa.Column('B', sa.Float(), nullable=True),
    sa.Column('W', sa.Float(), nullable=True),
    sa.Column('Pb', sa.Float(), nullable=True),
    sa.Column('Zn', sa.Float(), nullable=True),
    sa.Column('O', sa.Float(), nullable=True),
    sa.Column('N', sa.Float(), nullable=True),
    sa.Column('H', sa.Float(), nullable=True),
    sa.Column('As', sa.Float(), nullable=True),
    sa.Column('Sn', sa.Float(), nullable=True),
    sa.Column('Ceq', sa.Float(), nullable=True),
    sa.Column('Sb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_inspect_chem_heat_no'), 'fact_inspect_chem', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_inspect_chem_sample_lot_no'), 'fact_inspect_chem', ['sample_lot_no'], unique=False)
    op.create_table('fact_inspect_dim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_lot_no', sa.String(length=32), nullable=True),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('furnace_batch_no', sa.String(length=32), nullable=True),
    sa.Column('spec', sa.Float(), nullable=True),
    sa.Column('diagonal1', sa.Float(), nullable=True),
    sa.Column('diagonal2', sa.Float(), nullable=True),
    sa.Column('diag_diff', sa.Float(), nullable=True),
    sa.Column('curvature_per_m', sa.Float(), nullable=True),
    sa.Column('total_curvature', sa.Float(), nullable=True),
    sa.Column('dim_result', sa.String(length=16), nullable=True),
    sa.Column('appearance', sa.String(length=16), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('cold_upsetting', sa.String(length=16), nullable=True),
    sa.Column('conform_std', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_inspect_dim_heat_no'), 'fact_inspect_dim', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_inspect_dim_sample_lot_no'), 'fact_inspect_dim', ['sample_lot_no'], unique=False)
    op.create_table('fact_inspect_mech',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_lot_no', sa.String(length=32), nullable=True),
    sa.Column('sample_no', sa.String(length=16), nullable=True),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('steel_grade', sa.String(length=64), nullable=True),
    sa.Column('yield_strength', sa.Float(), nullable=True),
    sa.Column('tensile_strength', sa.Float(), nullable=True),
    sa.Column('elongation', sa.Float(), nullable=True),
    sa.Column('yield_ratio', sa.Float(), nullable=True),
    sa.Column('tensile_ratio', sa.Float(), nullable=True),
    sa.Column('reduction_area', sa.Float(), nullable=True),
    sa.Column('max_force_elong', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_inspect_mech_heat_no'), 'fact_inspect_mech', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_inspect_mech_sample_lot_no'), 'fact_inspect_mech', ['sample_lot_no'], unique=False)
    op.create_table('fact_rolling',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('furnace_batch_no', sa.String(length=32), nullable=True),
    sa.Column('material_no', sa.String(length=32), nullable=True),
    sa.Column('roll_plan_no', sa.String(length=32), nullable=True),
    sa.Column('steel_grade', sa.String(length=64), nullable=True),
    sa.Column('roll_start', sa.DateTime(), nullable=True),
    sa.Column('roll_end', sa.DateTime(), nullable=True),
    sa.Column('roll_time', sa.Float(), nullable=True),
    sa.Column('roll_count', sa.Float(), nullable=True),
    sa.Column('roll_weight', sa.Float(), nullable=True),
    sa.Column('start_roll_temp', sa.Float(), nullable=True),
    sa.Column('shear2_temp', sa.Float(), nullable=True),
    sa.Column('pre_finish_temp', sa.Float(), nullable=True),
    sa.Column('reduce_temp', sa.Float(), nullable=True),
    sa.Column('finish_temp', sa.Float(), nullable=True),
    sa.Column('laying_temp', sa.Float(), nullable=True),
    sa.Column('coolbed_temp', sa.Float(), nullable=True),
    sa.Column('hit_rate_a', sa.Float(), nullable=True),
    sa.Column('hit_rate_b', sa.Float(), nullable=True),
    sa.Column('hit_rate_c', sa.Float(), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('shift', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_rolling_furnace_batch_no'), 'fact_rolling', ['furnace_batch_no'], unique=False)
    op.create_index(op.f('ix_fact_rolling_heat_no'), 'fact_rolling', ['heat_no'], unique=False)
    op.create_table('fact_scrap_ratio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steel_grade', sa.String(length=64), nullable=False),
    sa.Column('scrap_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('heat_count', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_scrap_ratio_scrap_type'), 'fact_scrap_ratio', ['scrap_type'], unique=False)
    op.create_index(op.f('ix_fact_scrap_ratio_steel_grade'), 'fact_scrap_ratio', ['steel_grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_scrap_ratio_steel_grade'), table_name='fact_scrap_ratio')
    op.drop_index(op.f('ix_fact_scrap_ratio_scrap_type'), table_name='fact_scrap_ratio')
    op.drop_table('fact_scrap_ratio')
    op.drop_index(op.f('ix_fact_rolling_heat_no'), table_name='fact_rolling')
    op.drop_index(op.f('ix_fact_rolling_furnace_batch_no'), table_name='fact_rolling')
    op.drop_table('fact_rolling')
    op.drop_index(op.f('ix_fact_inspect_mech_sample_lot_no'), table_name='fact_inspect_mech')
    op.drop_index(op.f('ix_fact_inspect_mech_heat_no'), table_name='fact_inspect_mech')
    op.drop_table('fact_inspect_mech')
    op.drop_index(op.f('ix_fact_inspect_dim_sample_lot_no'), table_name='fact_inspect_dim')
    op.drop_index(op.f('ix_fact_inspect_dim_heat_no'), table_name='fact_inspect_dim')
    op.drop_table('fact_inspect_dim')
    op.drop_index(op.f('ix_fact_inspect_chem_sample_lot_no'), table_name='fact_inspect_chem')
    op.drop_index(op.f('ix_fact_inspect_chem_heat_no'), table_name='fact_inspect_chem')
    op.drop_table('fact_inspect_chem')
    op.drop_index(op.f('ix_fact_heating_heat_no'), table_name='fact_heating')
    op.drop_index(op.f('ix_fact_heating_furnace_batch_no'), table_name='fact_heating')
    op.drop_table('fact_heating')
    op.drop_index(op.f('ix_fact_heat_relation_sample_lot_no'), table_name='fact_heat_relation')
    op.drop_index(op.f('ix_fact_heat_relation_heat_no'), table_name='fact_heat_relation')
    op.drop_index(op.f('ix_fact_heat_relation_furnace_batch_no'), table_name='fact_heat_relation')
    op.drop_table('fact_heat_relation')
    op.drop_index(op.f('ix_fact_heat_indicator_tap_time'), table_name='fact_heat_indicator')
    op.drop_index(op.f('ix_fact_heat_indicator_steel_grade'), table_name='fact_heat_indicator')
    op.drop_index(op.f('ix_fact_heat_indicator_process'), table_name='fact_heat_indicator')
    op.drop_index(op.f('ix_fact_heat_indicator_judge'), table_name='fact_heat_indicator')
    op.drop_index(op.f('ix_fact_heat_indicator_indicator_name'), table_name='fact_heat_indicator')
    op.drop_index(op.f('ix_fact_heat_indicator_heat_no'), table_name='fact_heat_indicator')
    op.drop_table('fact_heat_indicator')
    op.drop_table('fact_heat')
    op.drop_table('dim_steel_grade')
    op.drop_table('dim_scrap_type')
    op.drop_table('dim_price')
    op.drop_table('dim_indicator')
    op.drop_table('dim_alloy')
    # ### end Alembic commands ###
