"""add dim packaging identification pickling

Revision ID: 8d0a6bb6cb75
Revises: 06899c059cb4
Create Date: 2026-07-25 08:51:34.029909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0a6bb6cb75'
down_revision: Union[str, None] = '06899c059cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_inspect_dim', sa.Column('packaging', sa.String(length=16), nullable=True))
    op.add_column('fact_inspect_dim', sa.Column('identification', sa.String(length=16), nullable=True))
    op.add_column('fact_inspect_dim', sa.Column('pickling', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_inspect_dim', 'pickling')
    op.drop_column('fact_inspect_dim', 'identification')
    op.drop_column('fact_inspect_dim', 'packaging')
    # ### end Alembic commands ###
