"""add fact_loss_detail

Revision ID: 95652df1d5bc
Revises: 8d0a6bb6cb75
Create Date: 2026-08-04 12:38:52.830702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95652df1d5bc'
down_revision: Union[str, None] = '8d0a6bb6cb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_loss_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heat_no', sa.String(length=32), nullable=True),
    sa.Column('steel_grade', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('equipment', sa.String(length=8), nullable=True),
    sa.Column('loss_category', sa.String(length=16), nullable=False),
    sa.Column('loss_name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heat_no', 'loss_name', name='uq_loss_detail')
    )
    op.create_index(op.f('ix_fact_loss_detail_heat_no'), 'fact_loss_detail', ['heat_no'], unique=False)
    op.create_index(op.f('ix_fact_loss_detail_loss_category'), 'fact_loss_detail', ['loss_category'], unique=False)
    op.create_index(op.f('ix_fact_loss_detail_loss_name'), 'fact_loss_detail', ['loss_name'], unique=False)
    op.create_index(op.f('ix_fact_loss_detail_steel_grade'), 'fact_loss_detail', ['steel_grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_loss_detail_steel_grade'), table_name='fact_loss_detail')
    op.drop_index(op.f('ix_fact_loss_detail_loss_name'), table_name='fact_loss_detail')
    op.drop_index(op.f('ix_fact_loss_detail_loss_category'), table_name='fact_loss_detail')
    op.drop_index(op.f('ix_fact_loss_detail_heat_no'), table_name='fact_loss_detail')
    op.drop_table('fact_loss_detail')
    # ### end Alembic commands ###
