"""add_ai_report_table

Revision ID: dd1b08f9f414
Revises: 95652df1d5bc
Create Date: 2026-08-05 02:08:36.333053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1b08f9f414'
down_revision: Union[str, None] = '95652df1d5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_report_domain_time', 'ai_report', ['domain', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_report_domain_time', table_name='ai_report')
    op.drop_table('ai_report')
    # ### end Alembic commands ###
